### ISSUE TITLE
The installation is broken.

### ISSUE THREAD

**Issue by simlevesque** [ElessarWebb/positron-bar#4]
Here is an example of what happens : https://asciinema.org/a/0qjgc66vs5vtlovzn7f0g4ltv

go to 2:20 to skip the actual install.

you must run the following command before gulping : `./node_modules/.bin/babel gulpfile.babel.js -o gulpfile.js`

**Comment by ajrouvoet** [comment]
`gulp` actually supports `gulpfile.babel.js`, but I'm not entirely sure what it requires that you are missing. Can you post the gulp version you're using?

**Comment by ajrouvoet** [comment]
The commit 708613ca387c1 should have fixed this, as the build no longer relies on the globally installed version of `gulp`. I've updated the readme accordingly. Can you try it out?

I've tried to build the package in a clean docker container and it succeeded.

**Comment by simlevesque** [comment]
Works 10/10.
